baseURL = "https://hypper.io/"
languageCode = "en-us"
theme = "portio-hugo"
title = "Hypper"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

[[menu.main]]
name = "Documentation"
url = "https://docs.hypper.io/"
weight = 1

[params]
# rename when the logo is updated, so we indirectly also invalidate caches
logo = "images/hypper-logo.png"
githubLink = "https://github.com/rancher-sandbox/hypper"
bookUrl = "https://docs.hypper.io/"
